import { readFileSync, writeFileSync } from 'node:fs'
import { randomBytes, createHash } from 'node:crypto'
import pg from 'pg'
import { createClient } from '@supabase/supabase-js'
import { app, database, tables, publicTables } from './settings.js'

const schema = JSON.parse(readFileSync(new URL('./source-schema.json', import.meta.url)))
const source = createClient(app.VITE_SUPABASE_URL, app.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false, autoRefreshToken: false } })
const quote = value => `"${value.replaceAll('"', '""')}"`
const connection = new pg.Client({ connectionString: database.DATABASE_URL, ssl: { ca: readFileSync(new URL('./database-ca.pem', import.meta.url)), checkServerIdentity: () => undefined } })
await connection.connect()
try {
  const existing = await connection.query("select count(*)::int count from information_schema.tables where table_schema='public' and table_type='BASE TABLE'")
  if (existing.rows[0].count) throw new Error('Destination is not empty. This copy never overwrites a test or live database.')
  const snapshot = {}
  for (const table of tables) {
    snapshot[table] = []
    for (let offset = 0; ; offset += 500) {
      const { data, error } = await source.from(table).select('*').order('id').range(offset, offset + 499)
      if (error) throw error
      snapshot[table].push(...data)
      if (data.length < 500) break
    }
  }
  writeFileSync(new URL('./snapshot.json', import.meta.url), JSON.stringify(snapshot))
  await connection.query('BEGIN')
  await connection.query(`CREATE ROLE cloudpeak_anon NOLOGIN; CREATE ROLE cloudpeak_user NOLOGIN; CREATE ROLE cloudpeak_admin NOLOGIN;
    CREATE SCHEMA auth; REVOKE ALL ON SCHEMA auth FROM PUBLIC;
    CREATE TABLE auth.users(id uuid PRIMARY KEY);
    CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claims',true)::jsonb->>'sub','')::uuid $$;
    CREATE FUNCTION auth.jwt() RETURNS jsonb LANGUAGE sql STABLE AS $$ SELECT coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb $$;
    GRANT USAGE ON SCHEMA public,auth TO cloudpeak_anon,cloudpeak_user,cloudpeak_admin;
    GRANT EXECUTE ON FUNCTION auth.uid(),auth.jwt() TO cloudpeak_anon,cloudpeak_user,cloudpeak_admin;`)
  for (const table of tables) {
    const columns = schema.columns.filter(column => column.table === table).map(column => `${quote(column.name)} ${column.type}${column.identity ? ' GENERATED BY DEFAULT AS IDENTITY' : column.default ? ` DEFAULT ${column.default}` : ''}${column.notnull ? ' NOT NULL' : ''}`)
    await connection.query(`CREATE TABLE public.${quote(table)} (${columns.join(',')})`)
  }
  for (const constraint of schema.constraints.filter(c => c.type !== 'f')) await connection.query(`ALTER TABLE public.${quote(constraint.table)} ADD CONSTRAINT ${quote(constraint.name)} ${constraint.definition}`)
  const userIds = new Set([...snapshot.profiles.map(row => row.id), ...snapshot.guest_payments.map(row => row.recorded_by).filter(Boolean)])
  for (const id of userIds) await connection.query('INSERT INTO auth.users(id) VALUES ($1)', [id])
  for (const table of tables) {
    for (const row of snapshot[table]) {
      const names = Object.keys(row)
      const values = names.map(name => {
        const column = schema.columns.find(column => column.table === table && column.name === name)
        return column?.type === 'jsonb' && row[name] !== null ? JSON.stringify(row[name]) : row[name]
      })
      await connection.query(`INSERT INTO public.${quote(table)} (${names.map(quote).join(',')}) VALUES (${names.map((_, i) => `$${i + 1}`).join(',')})`, values)
    }
    for (const column of schema.columns.filter(c => c.table === table && c.identity)) await connection.query(`SELECT setval(pg_get_serial_sequence($1,$2), coalesce((SELECT max(${quote(column.name)}) FROM public.${quote(table)}),1), EXISTS(SELECT 1 FROM public.${quote(table)}))`, [`public.${table}`, column.name])
  }
  for (const constraint of schema.constraints.filter(c => c.type === 'f')) await connection.query(`ALTER TABLE public.${quote(constraint.table)} ADD CONSTRAINT ${quote(constraint.name)} ${constraint.definition}`)
  for (const index of schema.indexes || []) await connection.query(index)
  for (const fn of schema.functions.filter(fn => fn.name !== 'handle_new_user')) await connection.query(fn.definition)
  for (const trigger of schema.triggers || []) await connection.query(trigger.definition)
  await connection.query('REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC')
  for (const table of tables) {
    await connection.query(`ALTER TABLE public.${quote(table)} ENABLE ROW LEVEL SECURITY;
      GRANT SELECT,INSERT,UPDATE,DELETE ON public.${quote(table)} TO cloudpeak_admin;
      CREATE POLICY admin_access ON public.${quote(table)} FOR ALL TO cloudpeak_admin USING(true) WITH CHECK(true);`)
    if (publicTables.has(table)) await connection.query(`GRANT SELECT ON public.${quote(table)} TO cloudpeak_anon,cloudpeak_user;
      CREATE POLICY public_read ON public.${quote(table)} FOR SELECT TO cloudpeak_anon,cloudpeak_user USING(true);`)
  }
  await connection.query(`GRANT SELECT ON public.profiles TO cloudpeak_user;
    CREATE POLICY own_profile ON public.profiles FOR SELECT TO cloudpeak_user USING(id=auth.uid());
    GRANT SELECT ON public.waitlist TO cloudpeak_user;
    GRANT UPDATE(selected_puppy_id,is_active,pending_approval) ON public.waitlist TO cloudpeak_user;
    CREATE POLICY own_waitlist_read ON public.waitlist FOR SELECT TO cloudpeak_user USING(lower(email)=lower(auth.jwt()->>'email'));
    CREATE POLICY own_waitlist_update ON public.waitlist FOR UPDATE TO cloudpeak_user USING(lower(email)=lower(auth.jwt()->>'email') AND is_active=true) WITH CHECK(lower(email)=lower(auth.jwt()->>'email'));
    GRANT INSERT ON public.applications,public.newsletter_signups,public.analytics_events TO cloudpeak_anon,cloudpeak_user;
    CREATE POLICY public_apply ON public.applications FOR INSERT TO cloudpeak_anon,cloudpeak_user WITH CHECK(status='new');
    CREATE POLICY public_newsletter ON public.newsletter_signups FOR INSERT TO cloudpeak_anon,cloudpeak_user WITH CHECK(true);
    CREATE POLICY public_analytics ON public.analytics_events FOR INSERT TO cloudpeak_anon,cloudpeak_user WITH CHECK(true);
    GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO cloudpeak_anon,cloudpeak_user,cloudpeak_admin;
    CREATE SCHEMA cloudpeak_internal; REVOKE ALL ON SCHEMA cloudpeak_internal FROM PUBLIC;
    CREATE TABLE cloudpeak_internal.test_copy(created_at timestamptz DEFAULT now(), source text NOT NULL);
    INSERT INTO cloudpeak_internal.test_copy(source) VALUES ('Supabase application snapshot for isolated testing');`)
  const password = randomBytes(32).toString('hex')
  await connection.query(`CREATE ROLE cloudpeak_api LOGIN NOINHERIT PASSWORD '${password}'; GRANT cloudpeak_anon,cloudpeak_user,cloudpeak_admin TO cloudpeak_api;`)
  await connection.query('COMMIT')
  const url = new URL(database.DATABASE_URL)
  url.username = 'cloudpeak_api'; url.password = password
  writeFileSync(new URL('./.env', import.meta.url), `DATABASE_URL=${JSON.stringify(database.DATABASE_URL)}\nAPI_DATABASE_URL=${JSON.stringify(url.href)}\n`)
  const report = { createdAt: new Date().toISOString(), tables: Object.fromEntries(tables.map(table => [table, { count: snapshot[table].length, sha256: createHash('sha256').update(JSON.stringify(snapshot[table])).digest('hex') }])) }
  writeFileSync(new URL('./copy-report.json', import.meta.url), JSON.stringify(report, null, 2))
  console.log('Copied all 14 application tables into an isolated Railway database; Supabase source is unchanged.')
} catch (error) {
  await connection.query('ROLLBACK').catch(() => {})
  throw error
} finally { await connection.end() }
